import { Plus, Trash2, SlidersHorizontal, Type, Move, Maximize2 } from 'lucide-react';
import type { BlurRegion, SubtitleStyle } from '@/types';
import { createBlurRegion } from '@/types';

interface Props {
  subtitleStyle: SubtitleStyle;
  blurEnabled: boolean;
  blurStrength: number;
  blurRegions: BlurRegion[];
  onSubtitleStyleChange: (style: SubtitleStyle) => void;
  onBlurEnabledChange: (enabled: boolean) => void;
  onBlurStrengthChange: (strength: number) => void;
  onBlurRegionsChange: (regions: BlurRegion[]) => void;
}

export function VideoEffectsEditor({ subtitleStyle, blurEnabled, blurStrength, blurRegions, onSubtitleStyleChange, onBlurEnabledChange, onBlurStrengthChange, onBlurRegionsChange }: Props) {
  const updateRegion = (id: string, patch: Partial<BlurRegion>) => onBlurRegionsChange(blurRegions.map((region) => region.id === id ? { ...region, ...patch } : region));
  return <div className="space-y-5 rounded-2xl border border-slate-800 bg-slate-900/60 p-4 sm:p-5">
    <div className="flex items-center justify-between rounded-xl border border-slate-800 bg-slate-950/40 p-3"><div className="flex items-center gap-2 text-sm font-semibold text-slate-200"><SlidersHorizontal className="h-5 w-5 text-emerald-400" /> Blur Tool</div><button aria-pressed={blurEnabled} onClick={() => onBlurEnabledChange(!blurEnabled)} className={`relative h-7 w-14 rounded-full transition-colors ${blurEnabled ? 'bg-emerald-500' : 'bg-slate-700'}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition-transform ${blurEnabled ? 'translate-x-8' : 'translate-x-1'}`} /></button></div>
    {blurEnabled && <div className="space-y-4 rounded-xl border border-slate-800 bg-slate-950/40 p-3"><label className="block text-sm text-slate-400">Blur Strength <span className="float-right font-medium text-slate-200">{blurStrength}%</span><input aria-label="Blur strength" type="range" min="0" max="100" value={blurStrength} onChange={(e) => onBlurStrengthChange(Number(e.target.value))} className="mt-3 w-full accent-emerald-500" /></label><div className="flex items-center justify-between"><p className="text-xs text-slate-500">Drag the green box on the video to move it. Drag the corner handle to resize.</p><button onClick={() => onBlurRegionsChange([...blurRegions, createBlurRegion()])} className="flex shrink-0 items-center gap-1 rounded-lg bg-emerald-500 px-3 py-2 text-xs font-semibold text-slate-950 hover:bg-emerald-400"><Plus className="h-3.5 w-3.5" /> Add area</button></div>{blurRegions.length === 0 && <button onClick={() => onBlurRegionsChange([createBlurRegion()])} className="w-full rounded-lg border border-dashed border-emerald-500/50 p-3 text-xs text-emerald-300 hover:bg-emerald-500/10">＋ Add your first blur area</button>}<div className="space-y-2">{blurRegions.map((region, index) => <div key={region.id} className="flex items-center justify-between rounded-lg bg-slate-900 p-2 text-xs"><span className="flex items-center gap-2 text-slate-300"><Move className="h-3.5 w-3.5 text-emerald-400" /> Blur area {index + 1}</span><div className="flex items-center gap-2"><button onClick={() => updateRegion(region.id, { enabled: !region.enabled })} className={`rounded px-2 py-1 ${region.enabled ? 'bg-emerald-500/20 text-emerald-300' : 'bg-slate-800 text-slate-500'}`}>{region.enabled ? 'On' : 'Off'}</button><button aria-label={`Delete blur area ${index + 1}`} onClick={() => onBlurRegionsChange(blurRegions.filter((item) => item.id !== region.id))} className="text-slate-500 hover:text-red-400"><Trash2 className="h-4 w-4" /></button></div></div>)}</div></div>}
    <div className="border-t border-slate-800 pt-4"><div className="mb-3 flex items-center gap-2 text-sm font-semibold text-slate-200"><Type className="h-4 w-4 text-sky-400" /> Subtitle appearance</div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><label className="text-xs text-slate-400">Font<select value={subtitleStyle.fontFamily} onChange={(e) => onSubtitleStyleChange({ ...subtitleStyle, fontFamily: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-800 px-3 py-2 text-sm text-slate-100">{['Arial', 'Tahoma', 'Verdana', 'Georgia', 'Trebuchet MS', 'Courier New'].map((font) => <option key={font}>{font}</option>)}</select></label><label className="text-xs text-slate-400">Font size: {subtitleStyle.fontSize}px<input type="range" min="16" max="64" value={subtitleStyle.fontSize} onChange={(e) => onSubtitleStyleChange({ ...subtitleStyle, fontSize: Number(e.target.value) })} className="mt-2 w-full accent-amber-500" /></label><label className="flex items-center gap-3 text-xs text-slate-400">Text color<input type="color" value={subtitleStyle.color} onChange={(e) => onSubtitleStyleChange({ ...subtitleStyle, color: e.target.value })} className="h-8 w-12 cursor-pointer rounded border-0 bg-transparent" /></label><label className="text-xs text-slate-400">Position: {subtitleStyle.position}%<input type="range" min="60" max="96" value={subtitleStyle.position} onChange={(e) => onSubtitleStyleChange({ ...subtitleStyle, position: Number(e.target.value) })} className="mt-2 w-full accent-amber-500" /></label></div></div>
  </div>;
}
